const fs = require('fs');
const path = require('path');

const cities = {
    amsterdam: [
        { id: 'amsterdam_rijksmuseum', name: 'Rijksmuseum', lat: 52.3600, lng: 4.8852, narration: '세계 최고의 미술관 중 하나인 레이크스뮤지엄에 오신 것을 환영합니다. 렘브란트의 야경을 비롯한 네덜란드 황금시대의 걸작들이 전시되어 있습니다.', description: "The Netherlands' premier art museum, home to Rembrandt's Night Watch.", category: 'Museum', photos: ['https://images.unsplash.com/photo-1583037189850-1921ae7c6c22?w=1200&q=80', 'https://images.unsplash.com/photo-1576924542622-772281b13aa8?w=1200&q=80', 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=1200&q=80'], tr: { ko: { name: '레이크스뮤지엄', desc: '렘브란트 야경이 있는 네덜란드 최고 미술관.' }, en: { name: 'Rijksmuseum', desc: "Netherlands' premier art museum featuring Rembrandt's Night Watch." }, ja: { name: 'アムステルダム国立美術館', desc: 'レンブラントの夜警を所蔵するオランダ最高の美術館。' }, 'zh-CN': { name: '荷兰国立博物馆', desc: '收藏伦勃朗《夜巡》的荷兰顶级艺术博物馆。' } }, kw: ['레이크스뮤지엄', '렘브란트', 'Rijksmuseum', 'Night Watch'] },
        { id: 'amsterdam_anne_frank', name: 'Anne Frank House', lat: 52.3752, lng: 4.8840, narration: '프린센흐라흐트 263번지, 안네 프랑크의 집 앞에 서 계십니다. 제2차 세계대전 중 나치의 박해를 피해 2년간 숨어 살았던 비밀의 공간입니다.', description: "Preserved secret annex where Anne Frank hid during WWII.", category: 'Historic Site', photos: ['https://images.unsplash.com/photo-1558551649-e44c8f992010?w=1200&q=80', 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=1200&q=80'], tr: { ko: { name: '안네 프랑크의 집', desc: 'WWII 당시 안네 프랑크가 숨어 살았던 비밀 별관.' }, en: { name: 'Anne Frank House', desc: "Secret annex where Anne Frank wrote her diary during WWII." }, ja: { name: 'アンネ・フランクの家', desc: '第二次大戦中にアンネ・フランクが隠れ住んだ秘密の別館。' }, 'zh-CN': { name: '安妮·弗兰克之家', desc: '二战期间安妮·弗兰克藏身的秘密阁楼。' } }, kw: ['안네 프랑크', 'Anne Frank', 'WWII'] },
        { id: 'amsterdam_canal_cruise', name: 'Canal Cruise', lat: 52.3702, lng: 4.8952, narration: '17세기 황금시대에 건설된 암스테르담 운하를 유람선으로 둘러보는 특별한 체험입니다. 유네스코 세계문화유산으로 지정된 운하 벨트입니다.', description: "UNESCO World Heritage canal cruise through Amsterdam's waterways.", category: 'Activity', photos: ['https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=1200&q=80', 'https://images.unsplash.com/photo-1576924542622-772281b13aa8?w=1200&q=80'], tr: { ko: { name: '암스테르담 운하 크루즈', desc: '유네스코 세계문화유산 운하를 따라가는 크루즈.' }, en: { name: 'Canal Cruise', desc: "Cruise through UNESCO World Heritage canals." }, ja: { name: '運河クルーズ', desc: 'ユネスコ世界遺産の運河を巡るクルーズ。' }, 'zh-CN': { name: '运河游船', desc: '游览联合国教科文组织世界遗产运河。' } }, kw: ['운하 크루즈', 'canal cruise', 'UNESCO'] },
        { id: 'amsterdam_vondelpark', name: 'Vondelpark', lat: 52.3579, lng: 4.8686, narration: '암스테르담 시민들이 가장 사랑하는 녹색 오아시스, 펀델파크에 오신 것을 환영합니다. 47헥타르에 달하는 도시의 심장입니다.', description: "Amsterdam's beloved 47-hectare urban park.", category: 'Nature', photos: ['https://images.unsplash.com/photo-1558551649-e44c8f992010?w=1200&q=80', 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=1200&q=80'], tr: { ko: { name: '펀델파크', desc: '암스테르담 중심부의 47헥타르 도시 공원.' }, en: { name: 'Vondelpark', desc: "Amsterdam's beloved 47-hectare urban park." }, ja: { name: 'フォンデル公園', desc: 'アムステルダム中心部の47ヘクタールの都市公園。' }, 'zh-CN': { name: '冯德尔公园', desc: '阿姆斯特丹市中心的47公顷城市公园。' } }, kw: ['펀델파크', 'Vondelpark', 'Amsterdam park'] }
    ],
    budapest: [
        { id: 'budapest_parliament', name: 'Hungarian Parliament Building', lat: 47.5073, lng: 19.0458, narration: '다뉴브 강변에 우뚝 솟은 헝가리 국회의사당은 유럽에서 가장 아름다운 건물 중 하나입니다. 691개 객실과 96m 높이의 돔을 자랑합니다.', description: "Neo-Gothic masterpiece on the Danube, one of Europe's most spectacular parliament buildings.", category: 'Landmark', photos: ['https://images.unsplash.com/photo-1549923746-c502d488b3ea?w=1200&q=80', 'https://images.unsplash.com/photo-1551867633-194f125bddfa?w=1200&q=80'], tr: { ko: { name: '헝가리 국회의사당', desc: '다뉴브 강변의 네오고딕 걸작.' }, en: { name: 'Hungarian Parliament Building', desc: 'Spectacular Neo-Gothic parliament on the Danube.' }, ja: { name: 'ハンガリー国会議事堂', desc: 'ドナウ川沿いのネオゴシック傑作。' }, 'zh-CN': { name: '匈牙利国会大厦', desc: '多瑙河畔的新哥特式杰作。' } }, kw: ['국회의사당', '부다페스트', 'Parliament', 'Budapest'] },
        { id: 'budapest_szechenyi_baths', name: 'Széchenyi Thermal Baths', lat: 47.5188, lng: 19.0822, narration: '유럽 최대 규모의 공공 온천인 세체니 온천에 오신 것을 환영합니다. 1913년 개장 이래 18개의 풀과 사우나를 갖추고 있습니다.', description: "Europe's largest public thermal bath complex since 1913.", category: 'Activity', photos: ['https://images.unsplash.com/photo-1551867633-194f125bddfa?w=1200&q=80', 'https://images.unsplash.com/photo-1549923746-c502d488b3ea?w=1200&q=80'], tr: { ko: { name: '세체니 온천', desc: '1913년 개장, 유럽 최대 공공 온천.' }, en: { name: 'Széchenyi Thermal Baths', desc: "Europe's largest thermal bath since 1913." }, ja: { name: 'セーチェニ温泉', desc: '1913年開業、ヨーロッパ最大の公共温泉。' }, 'zh-CN': { name: '塞切尼温泉', desc: '1913年开业的欧洲最大公共温泉。' } }, kw: ['세체니 온천', 'Széchenyi', 'thermal bath'] },
        { id: 'budapest_fishermans_bastion', name: "Fisherman's Bastion", lat: 47.5019, lng: 19.0348, narration: '부다 성 언덕 위 어부의 요새에서 다뉴브 강과 페스트 시가지의 파노라마를 감상하세요. 7개의 하얀 탑은 마자르 7부족을 상징합니다.', description: "Fairy-tale Neo-Romanesque terrace on Castle Hill with Danube panoramas.", category: 'Landmark', photos: ['https://images.unsplash.com/photo-1565426873118-a17ed65d74b9?w=1200&q=80', 'https://images.unsplash.com/photo-1549923746-c502d488b3ea?w=1200&q=80'], tr: { ko: { name: '어부의 요새', desc: '다뉴브 강 파노라마를 선사하는 동화 같은 전망대.' }, en: { name: "Fisherman's Bastion", desc: 'Fairy-tale terrace with Danube panoramas.' }, ja: { name: '漁夫の砦', desc: 'ドナウ川パノラマの展望テラス。' }, 'zh-CN': { name: '渔夫堡', desc: '多瑙河全景的童话般观景台。' } }, kw: ['어부의 요새', "Fisherman's Bastion", 'Castle Hill'] },
        { id: 'budapest_ruin_bars', name: 'Szimpla Kert Ruin Bar', lat: 47.4974, lng: 19.0629, narration: '부다페스트 루인 바의 원조 심플라 케르트에 오신 것을 환영합니다. 2002년 버려진 공장을 개조해 만든 독특한 바입니다.', description: "The original Budapest ruin bar in a converted factory.", category: 'Cultural Site', photos: ['https://images.unsplash.com/photo-1551867633-194f125bddfa?w=1200&q=80'], tr: { ko: { name: '심플라 케르트 루인 바', desc: '부다페스트 루인 바 문화의 원조.' }, en: { name: 'Szimpla Kert Ruin Bar', desc: 'The pioneering ruin bar in a converted factory.' }, ja: { name: 'シンプラ・ケルト', desc: 'ブダペスト廃墟バー文化の元祖。' }, 'zh-CN': { name: '辛普拉花园', desc: '布达佩斯废墟酒吧文化发源地。' } }, kw: ['루인 바', 'Szimpla', 'ruin bar'] }
    ],
    warsaw: [
        { id: 'warsaw_old_town', name: 'Warsaw Old Town', lat: 52.2496, lng: 21.0122, narration: '제2차 세계대전 중 85% 이상 파괴되었다가 시민들의 노력으로 완벽 복원된 유네스코 세계문화유산 바르샤바 구시가지입니다.', description: "UNESCO World Heritage old town, rebuilt after WWII from 85% destruction.", category: 'Historic Site', photos: ['https://images.unsplash.com/photo-1519197924294-4ba991a11128?w=1200&q=80', 'https://images.unsplash.com/photo-1607427293702-036707e560d7?w=1200&q=80'], tr: { ko: { name: '바르샤바 구시가지', desc: 'WWII 후 복원된 유네스코 세계문화유산.' }, en: { name: 'Warsaw Old Town', desc: 'UNESCO Heritage old town rebuilt after WWII.' }, ja: { name: 'ワルシャワ旧市街', desc: '第二次大戦後に再建されたユネスコ世界遺産。' }, 'zh-CN': { name: '华沙老城', desc: '二战后精心重建的世界遗产老城。' } }, kw: ['바르샤바 구시가지', 'Warsaw Old Town', 'UNESCO'] },
        { id: 'warsaw_wilanow_palace', name: 'Wilanów Palace', lat: 52.1654, lng: 21.0904, narration: '폴란드의 베르사유라 불리는 빌라누프 궁전. 1677년 얀 3세 소비에스키 왕이 건설한 바로크 여름 별궁입니다.', description: "The Polish Versailles — Baroque summer palace built 1677.", category: 'Landmark', photos: ['https://images.unsplash.com/photo-1607427293702-036707e560d7?w=1200&q=80'], tr: { ko: { name: '빌라누프 궁전', desc: '1677년 건설된 폴란드의 베르사유.' }, en: { name: 'Wilanów Palace', desc: 'Magnificent Baroque palace built 1677.' }, ja: { name: 'ヴィラヌフ宮殿', desc: '1677年建設のバロック宮殿。' }, 'zh-CN': { name: '维拉诺夫宫', desc: '1677年建造的巴洛克夏宫。' } }, kw: ['빌라누프', 'Wilanów', 'Polish Versailles'] }
    ],
    copenhagen: [
        { id: 'copenhagen_nyhavn', name: 'Nyhavn Waterfront', lat: 55.6796, lng: 12.5893, narration: '코펜하겐의 상징 뉘하운 항구. 17세기에 건설된 항구를 따라 다채로운 타운하우스들이 줄지어 있으며, 안데르센이 살았던 집도 이곳에 있습니다.', description: "Copenhagen's iconic harbor with colorful townhouses.", category: 'Landmark', photos: ['https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=1200&q=80', 'https://images.unsplash.com/photo-1552560880-2482d4b1e4e2?w=1200&q=80'], tr: { ko: { name: '뉘하운 항구', desc: '안데르센 고향의 다채로운 17세기 항구.' }, en: { name: 'Nyhavn Waterfront', desc: 'Iconic harbor with colorful townhouses.' }, ja: { name: 'ニューハウン港', desc: 'アンデルセンが住んだカラフルな港。' }, 'zh-CN': { name: '新港', desc: '安徒生故居所在的彩色建筑港口。' } }, kw: ['뉘하운', 'Nyhavn', 'Copenhagen', '안데르센'] },
        { id: 'copenhagen_tivoli', name: 'Tivoli Gardens', lat: 55.6737, lng: 12.5681, narration: '1843년 개장, 세계에서 두 번째로 오래된 놀이공원. 월트 디즈니가 디즈니랜드의 영감을 받은 곳입니다.', description: "World's second-oldest amusement park (1843), Disney's inspiration.", category: 'Activity', photos: ['https://images.unsplash.com/photo-1552560880-2482d4b1e4e2?w=1200&q=80'], tr: { ko: { name: '티볼리 가든', desc: '디즈니랜드의 모델이 된 1843년 놀이공원.' }, en: { name: 'Tivoli Gardens', desc: "World's second-oldest park, Disney's inspiration." }, ja: { name: 'チボリ公園', desc: 'ディズニーランドのモデルの遊園地。' }, 'zh-CN': { name: '趣伏里花园', desc: '启发迪士尼乐园的世界第二古老游乐园。' } }, kw: ['티볼리', 'Tivoli', 'Disney inspiration'] }
    ],
    oslo: [
        { id: 'oslo_opera_house', name: 'Oslo Opera House', lat: 59.9077, lng: 10.7529, narration: '오슬로 피오르드 가장자리의 대리석 지붕 위를 걸어 올라갈 수 있는 현대 건축의 걸작입니다.', description: "Award-winning opera house with walkable marble roof on Oslo Fjord.", category: 'Landmark', photos: ['https://images.unsplash.com/photo-1533929736562-87b04b9ca07a?w=1200&q=80', 'https://images.unsplash.com/photo-1559629819-638a8f0a4303?w=1200&q=80'], tr: { ko: { name: '오슬로 오페라하우스', desc: '걸어 올라갈 수 있는 대리석 지붕의 오페라하우스.' }, en: { name: 'Oslo Opera House', desc: 'Iconic opera house with walkable roof on the fjord.' }, ja: { name: 'オスロ・オペラハウス', desc: '歩行可能な大理石屋根のオペラハウス。' }, 'zh-CN': { name: '奥斯陆歌剧院', desc: '可步行上屋顶的标志性歌剧院。' } }, kw: ['오페라하우스', 'Oslo Opera House'] },
        { id: 'oslo_vigeland_park', name: 'Vigeland Sculpture Park', lat: 59.9269, lng: 10.7008, narration: '세계 최대의 단일 작가 조각 공원. 구스타프 비겔란의 212점 조각품이 전시되어 있습니다.', description: "World's largest single-artist sculpture park with 212 works.", category: 'Cultural Site', photos: ['https://images.unsplash.com/photo-1559629819-638a8f0a4303?w=1200&q=80'], tr: { ko: { name: '비겔란 조각 공원', desc: '212점 조각의 세계 최대 단일 작가 공원.' }, en: { name: 'Vigeland Sculpture Park', desc: '212 sculptures by Gustav Vigeland.' }, ja: { name: 'ヴィーゲラン彫刻公園', desc: '212作品の世界最大彫刻公園。' }, 'zh-CN': { name: '维格兰雕塑公园', desc: '212件雕塑的世界最大雕塑公园。' } }, kw: ['비겔란', 'Vigeland', 'sculpture park'] }
    ],
    brussels: [
        { id: 'brussels_grand_place', name: 'Grand-Place', lat: 50.8467, lng: 4.3525, narration: '유네스코 세계문화유산이자 빅토르 위고가 세계에서 가장 아름다운 광장이라 극찬한 그랑플라스입니다.', description: "UNESCO World Heritage square praised by Victor Hugo as world's most beautiful.", category: 'Landmark', photos: ['https://images.unsplash.com/photo-1559113513-d5e09c78a5ab?w=1200&q=80', 'https://images.unsplash.com/photo-1562228378-b1f3a7ee8a07?w=1200&q=80'], tr: { ko: { name: '그랑플라스', desc: '위고가 극찬한 유네스코 세계문화유산 광장.' }, en: { name: 'Grand-Place', desc: 'UNESCO square praised by Victor Hugo.' }, ja: { name: 'グラン＝プラス', desc: 'ユーゴーが絶賛したユネスコ世界遺産広場。' }, 'zh-CN': { name: '大广场', desc: '雨果赞誉的世界遗产广场。' } }, kw: ['그랑플라스', 'Grand-Place', 'Brussels', 'UNESCO'] },
        { id: 'brussels_atomium', name: 'Atomium', lat: 50.8948, lng: 4.3418, narration: '1958년 세계 박람회를 위해 건설된 철 결정 구조를 1650억 배로 확대한 102m 높이의 아토미움입니다.', description: "Iconic 102m structure of nine spheres, built for 1958 World Expo.", category: 'Landmark', photos: ['https://images.unsplash.com/photo-1562228378-b1f3a7ee8a07?w=1200&q=80'], tr: { ko: { name: '아토미움', desc: '1958년 세계 박람회의 상징, 102m 구조물.' }, en: { name: 'Atomium', desc: 'Iconic 102m structure for Expo 1958.' }, ja: { name: 'アトミウム', desc: '1958年万博の102m構造物。' }, 'zh-CN': { name: '原子球塔', desc: '1958年世博会标志102米建筑。' } }, kw: ['아토미움', 'Atomium', '1958 Expo'] }
    ],
    prague: [
        { id: 'prague_charles_bridge', name: 'Charles Bridge', lat: 50.0865, lng: 14.4114, narration: '1357년 카를 4세의 명에 의해 건설된 카를교. 블타바 강 위 30개의 바로크 성인 조각상이 늘어선 고딕 석조 다리입니다.', description: "Gothic 14th-century bridge with 30 Baroque saint statues spanning the Vltava.", category: 'Landmark', photos: ['https://images.unsplash.com/photo-1541849546-216549ae216d?w=1200&q=80', 'https://images.unsplash.com/photo-1562624475-96c2bc08fab9?w=1200&q=80'], tr: { ko: { name: '카를교', desc: '30개 성인 조각이 있는 14세기 고딕 석조 다리.' }, en: { name: 'Charles Bridge', desc: '14th-century bridge with 30 Baroque saint statues.' }, ja: { name: 'カレル橋', desc: '30体の聖人像が並ぶ14世紀のゴシック石橋。' }, 'zh-CN': { name: '查理大桥', desc: '30座圣人雕像的14世纪哥特式石桥。' } }, kw: ['카를교', 'Charles Bridge', 'Prague'] },
        { id: 'prague_old_town_square', name: 'Old Town Square & Astronomical Clock', lat: 50.0873, lng: 14.4213, narration: '1410년 제작된 세계에서 가장 오래된 작동 중인 천문 시계가 있는 프라하 구시가지 광장입니다.', description: "Prague's medieval heart with the 1410 Astronomical Clock.", category: 'Historic Site', photos: ['https://images.unsplash.com/photo-1562624475-96c2bc08fab9?w=1200&q=80'], tr: { ko: { name: '구시가지 광장 & 천문 시계', desc: '1410년 세계 최고(最古) 천문 시계가 있는 프라하 중심.' }, en: { name: 'Old Town Square & Astronomical Clock', desc: "World's oldest operating astronomical clock from 1410." }, ja: { name: '旧市街広場＆天文時計', desc: '1410年の世界最古の天文時計。' }, 'zh-CN': { name: '老城广场与天文钟', desc: '1410年的世界最古老运行天文钟。' } }, kw: ['천문 시계', 'Astronomical Clock', 'Prague', '1410'] }
    ],
    stockholm: [
        { id: 'stockholm_gamla_stan', name: 'Gamla Stan (Old Town)', lat: 59.3252, lng: 18.0710, narration: '13세기에 형성된 스톡홀름의 구시가지 감라 스탄. 발트해의 섬 위에 자리한 중세 마을로 왕궁과 노벨 박물관이 있습니다.', description: "Stockholm's 13th-century island old town with Royal Palace and Nobel Museum.", category: 'Historic Site', photos: ['https://images.unsplash.com/photo-1509356843151-3e7d96241e11?w=1200&q=80', 'https://images.unsplash.com/photo-1572883454114-efb8e12fd1a2?w=1200&q=80'], tr: { ko: { name: '감라 스탄', desc: '왕궁, 노벨 박물관이 있는 13세기 섬 구시가지.' }, en: { name: 'Gamla Stan', desc: '13th-century island old town with Royal Palace.' }, ja: { name: 'ガムラスタン', desc: '王宮がある13世紀の島の旧市街。' }, 'zh-CN': { name: '老城岛', desc: '拥有王宫的13世纪岛屿老城。' } }, kw: ['감라 스탄', 'Gamla Stan', 'Stockholm'] },
        { id: 'stockholm_vasa_museum', name: 'Vasa Museum', lat: 59.3280, lng: 18.0914, narration: '1628년 처녀 항해에서 침몰한 군함 바사호가 333년 만에 해저에서 인양되어 전시된 박물관입니다.', description: "Museum housing the 1628 Vasa warship, salvaged 333 years later nearly intact.", category: 'Museum', photos: ['https://images.unsplash.com/photo-1572883454114-efb8e12fd1a2?w=1200&q=80'], tr: { ko: { name: '바사 박물관', desc: '1628년 침몰, 333년 후 인양된 전함 박물관.' }, en: { name: 'Vasa Museum', desc: '1628 warship salvaged after 333 years.' }, ja: { name: 'ヴァーサ号博物館', desc: '333年ぶりに引き揚げられた17世紀軍艦。' }, 'zh-CN': { name: '瓦萨博物馆', desc: '333年后打捞的17世纪战舰博物馆。' } }, kw: ['바사 박물관', 'Vasa Museum', '1628'] }
    ]
};

function buildLandmark(cityId, lm) {
    return {
        id: lm.id, cityId, name: lm.name, lat: lm.lat, lng: lm.lng, radius: 80,
        narration: lm.narration, description: lm.description, category: lm.category,
        detailedDescription: null,
        photos: lm.photos,
        historicalInfo: null, yearBuilt: null, architect: null,
        translations: Object.fromEntries(Object.entries(lm.tr).map(([lang, t]) => [lang, { name: t.name, narration: lm.narration, description: t.desc }])),
        openingHours: null, priceRange: null, cuisine: null, reservationUrl: null,
        phoneNumber: null, menuHighlights: null, restaurantPhotos: null, paymentMethods: null,
        searchKeywords: lm.kw, isPremium: false, price: null,
        createdAt: 'new Date("2026-04-22T00:00:00.000Z")',
        updatedAt: 'new Date("2026-04-22T00:00:00.000Z")'
    };
}

let lines = ['import { type Landmark } from "../../shared/schema";', '', 'export const LANDMARKS_EU_BOOST: Landmark[] = ['];
for (const [cityId, landmarks] of Object.entries(cities)) {
    lines.push(`  // ===== ${cityId.toUpperCase()} =====`);
    for (const lm of landmarks) {
        const obj = buildLandmark(cityId, lm);
        const json = JSON.stringify(obj, null, 4)
            .replace(/"new Date\(\\"(.*?)\\"\)"/g, 'new Date("$1")')
            .split('\n').map((l, i) => i === 0 ? '  ' + l : '  ' + l).join('\n');
        lines.push(json + ',');
    }
}
lines.push('];', '');

const outPath = path.join(process.cwd(), 'server', 'data', 'landmarks_eu_boost.ts');
fs.writeFileSync(outPath, lines.join('\n'), 'utf-8');
console.log(`✅ EU Boost: ${outPath} (${lines.length} lines, ${Object.values(cities).flat().length} landmarks)`);
