/**
 * EU Boost 랜드마크 데이터 생성 스크립트
 * 실행: npx ts-node scripts/generate-eu-landmarks.ts
 */
import * as fs from 'fs';
import * as path from 'path';

interface CityLandmark {
    id: string; cityId: string; name: string; lat: number; lng: number;
    narration: string; description: string; category: string;
    photos: string[]; translations: any; searchKeywords: string[];
}

const cities: Record<string, { lat: number; lng: number; landmarks: Omit<CityLandmark, 'cityId'>[] }> = {
    amsterdam: {
        lat: 52.3676, lng: 4.9041, landmarks: [
            { id: 'amsterdam_rijksmuseum', name: 'Rijksmuseum', lat: 52.3600, lng: 4.8852, narration: '세계 최고의 미술관 중 하나인 레이크스뮤지엄에 오신 것을 환영합니다. 렘브란트의 야경을 비롯한 네덜란드 황금시대의 걸작들이 이곳에 전시되어 있습니다. 1885년 개관 이래 네덜란드 예술과 역사의 보고로, 80개 전시실에 8,000여 점의 예술품이 시간의 흐름을 따라 펼쳐집니다.', description: 'The Netherlands\' premier art museum, home to Rembrandt\'s Night Watch and Vermeer masterpieces.', category: 'Museum', photos: ['https://images.unsplash.com/photo-1583037189850-1921ae7c6c22?w=1200&q=80', 'https://images.unsplash.com/photo-1576924542622-772281b13aa8?w=1200&q=80', 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=1200&q=80'], translations: { ko: { name: '레이크스뮤지엄', narration: '세계 최고의 미술관 중 하나인 레이크스뮤지엄에 오신 것을 환영합니다.', description: '렘브란트 야경과 베르메르 걸작이 있는 네덜란드 최고 미술관.' }, en: { name: 'Rijksmuseum', narration: 'Welcome to the Rijksmuseum, the crown jewel of Dutch art and history.', description: 'The Netherlands\' premier art museum featuring Rembrandt\'s Night Watch.' }, ja: { name: 'アムステルダム国立美術館', narration: 'オランダ美術の最高峰、アムステルダム国立美術館へようこそ。', description: 'レンブラントの夜警を所蔵するオランダ最高の美術館。' }, 'zh-CN': { name: '荷兰国立博物馆', narration: '欢迎来到荷兰国立博物馆，这里是荷兰艺术的最高殿堂。', description: '收藏伦勃朗《夜巡》的荷兰顶级艺术博物馆。' } }, searchKeywords: ['레이크스뮤지엄', '렘브란트', '야경', '암스테르담 미술관', 'Rijksmuseum', 'Rembrandt', 'Night Watch'] },
            { id: 'amsterdam_anne_frank', name: 'Anne Frank House', lat: 52.3752, lng: 4.8840, narration: '프린센흐라흐트 263번지, 안네 프랑크의 집 앞에 서 계십니다. 제2차 세계대전 중 나치의 유대인 박해를 피해 2년간 숨어 살았던 이 비밀의 공간은 인류 역사에서 가장 가슴 아픈 이야기 중 하나를 간직하고 있습니다.', description: 'The preserved secret annex where Anne Frank hid during WWII, now one of the world\'s most visited museums.', category: 'Historic Site', photos: ['https://images.unsplash.com/photo-1558551649-e44c8f992010?w=1200&q=80', 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=1200&q=80', 'https://images.unsplash.com/photo-1583037189850-1921ae7c6c22?w=1200&q=80'], translations: { ko: { name: '안네 프랑크의 집', narration: '안네 프랑크가 2년간 숨어 살았던 비밀의 공간입니다.', description: '제2차 세계대전 당시 안네 프랑크가 숨어 살았던 비밀 별관.' }, en: { name: 'Anne Frank House', narration: 'Standing before 263 Prinsengracht, the Anne Frank House.', description: 'The secret annex where Anne Frank wrote her diary during WWII.' }, ja: { name: 'アンネ・フランクの家', narration: 'アンネ・フランクが2年間隠れ住んだ秘密の部屋の前に立っています。', description: '第二次世界大戦中にアンネ・フランクが隠れ住んだ秘密の別館。' }, 'zh-CN': { name: '安妮·弗兰克之家', narration: '您正站在安妮·弗兰克藏身两年的秘密阁楼前。', description: '二战期间安妮·弗兰克藏身的秘密阁楼，如今是世界最受瞩目的博物馆之一。' } }, searchKeywords: ['안네 프랑크', '암스테르담', 'Anne Frank', 'WWII', 'secret annex'] },
            { id: 'amsterdam_canal_cruise', name: 'Canal Cruise', lat: 52.3702, lng: 4.8952, narration: '17세기 황금시대에 건설된 암스테르담 운하를 유람선으로 둘러보는 특별한 체험입니다. 유네스코 세계문화유산으로 지정된 이 운하 벨트는 100km 이상의 수로와 1,500개의 다리로 이루어져 있습니다.', description: 'UNESCO World Heritage canal cruise through Amsterdam\'s 17th-century waterways.', category: 'Activity', photos: ['https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=1200&q=80', 'https://images.unsplash.com/photo-1576924542622-772281b13aa8?w=1200&q=80', 'https://images.unsplash.com/photo-1558551649-e44c8f992010?w=1200&q=80'], translations: { ko: { name: '암스테르담 운하 크루즈', narration: '17세기 황금시대에 건설된 운하를 유람선으로 둘러봅니다.', description: '유네스코 세계문화유산 운하를 따라가는 크루즈 투어.' }, en: { name: 'Canal Cruise', narration: 'Glide through Amsterdam\'s iconic 17th-century canal belt.', description: 'Cruise through UNESCO World Heritage canals of Amsterdam.' }, ja: { name: 'アムステルダム運河クルーズ', narration: '17世紀に建設されたアムステルダムの運河をクルーズで巡ります。', description: 'ユネスコ世界遺産の運河を巡るクルーズツアー。' }, 'zh-CN': { name: '阿姆斯特丹运河游船', narration: '乘坐游船穿越17世纪建造的阿姆斯特丹运河。', description: '游览联合国教科文组织世界遗产运河的游船之旅。' } }, searchKeywords: ['운하 크루즈', '암스테르담', 'canal cruise', 'UNESCO', '운하 벨트'] },
            { id: 'amsterdam_vondelpark', name: 'Vondelpark', lat: 52.3579, lng: 4.8686, narration: '암스테르담 시민들이 가장 사랑하는 녹색 오아시스, 펀델파크에 오신 것을 환영합니다. 47헥타르에 달하는 이 공원은 연간 1,000만 명이 방문하는 도시의 심장입니다.', description: 'Amsterdam\'s beloved 47-hectare urban park, a green oasis in the heart of the city.', category: 'Nature', photos: ['https://images.unsplash.com/photo-1558551649-e44c8f992010?w=1200&q=80', 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=1200&q=80', 'https://images.unsplash.com/photo-1576924542622-772281b13aa8?w=1200&q=80'], translations: { ko: { name: '펀델파크', narration: '암스테르담 시민들이 사랑하는 녹색 오아시스입니다.', description: '암스테르담 중심부의 47헥타르 도시 공원.' }, en: { name: 'Vondelpark', narration: 'Welcome to Vondelpark, Amsterdam\'s green heart.', description: 'Amsterdam\'s beloved 47-hectare urban park with 10 million annual visitors.' }, ja: { name: 'フォンデル公園', narration: 'アムステルダム市民に愛される緑のオアシスへようこそ。', description: 'アムステルダム中心部の47ヘクタールの都市公園。' }, 'zh-CN': { name: '冯德尔公园', narration: '欢迎来到阿姆斯特丹市民最喜爱的绿洲冯德尔公园。', description: '阿姆斯特丹市中心的47公顷城市公园。' } }, searchKeywords: ['펀델파크', '암스테르담 공원', 'Vondelpark', 'Amsterdam park'] }
        ]
    },
    budapest: {
        lat: 47.4979, lng: 19.0402, landmarks: [
            { id: 'budapest_parliament', name: 'Hungarian Parliament Building', lat: 47.5073, lng: 19.0458, narration: '다뉴브 강변에 우뚝 솟은 헝가리 국회의사당은 유럽에서 가장 아름다운 국회의사당 건물 중 하나입니다. 네오고딕 양식의 이 웅장한 건축물은 691개의 객실과 96m 높이의 돔을 자랑합니다.', description: 'Neo-Gothic masterpiece on the Danube, one of Europe\'s most spectacular parliament buildings.', category: 'Landmark', photos: ['https://images.unsplash.com/photo-1549923746-c502d488b3ea?w=1200&q=80', 'https://images.unsplash.com/photo-1551867633-194f125bddfa?w=1200&q=80', 'https://images.unsplash.com/photo-1565426873118-a17ed65d74b9?w=1200&q=80'], translations: { ko: { name: '헝가리 국회의사당', narration: '다뉴브 강변의 웅장한 네오고딕 양식 국회의사당입니다.', description: '다뉴브 강변의 네오고딕 걸작, 유럽에서 가장 아름다운 국회의사당.' }, en: { name: 'Hungarian Parliament Building', narration: 'The magnificent Neo-Gothic Hungarian Parliament rises along the Danube.', description: 'Spectacular Neo-Gothic parliament on the Danube with 691 rooms and a 96m dome.' }, ja: { name: 'ハンガリー国会議事堂', narration: 'ドナウ川沿いに壮麗にそびえるネオゴシック様式の国会議事堂です。', description: 'ドナウ川沿いのネオゴシック傑作、欧州で最も美しい国会議事堂の一つ。' }, 'zh-CN': { name: '匈牙利国会大厦', narration: '矗立于多瑙河畔的新哥特式杰作匈牙利国会大厦。', description: '多瑙河畔的新哥特式杰作，欧洲最壮观的国会大厦之一。' } }, searchKeywords: ['국회의사당', '부다페스트', 'Parliament', 'Budapest', '다뉴브'] },
            { id: 'budapest_szechenyi_baths', name: 'Széchenyi Thermal Baths', lat: 47.5188, lng: 19.0822, narration: '유럽 최대 규모의 공공 온천인 세체니 온천에 오신 것을 환영합니다. 1913년 개장 이래 부다페스트 시민과 여행자 모두에게 사랑받는 이곳은 노란색 네오바로크 건물 안에 18개의 풀과 다양한 사우나를 갖추고 있습니다.', description: 'Europe\'s largest public thermal bath complex, a stunning Neo-Baroque masterpiece since 1913.', category: 'Activity', photos: ['https://images.unsplash.com/photo-1551867633-194f125bddfa?w=1200&q=80', 'https://images.unsplash.com/photo-1549923746-c502d488b3ea?w=1200&q=80', 'https://images.unsplash.com/photo-1565426873118-a17ed65d74b9?w=1200&q=80'], translations: { ko: { name: '세체니 온천', narration: '유럽 최대의 공공 온천 세체니에 오신 것을 환영합니다.', description: '1913년 개장, 유럽 최대의 공공 온천 단지.' }, en: { name: 'Széchenyi Thermal Baths', narration: 'Welcome to Europe\'s largest public thermal bath.', description: 'Europe\'s largest thermal bath complex in a Neo-Baroque palace since 1913.' }, ja: { name: 'セーチェニ温泉', narration: 'ヨーロッパ最大の公共温泉セーチェニへようこそ。', description: '1913年開業、ヨーロッパ最大の公共温泉施設。' }, 'zh-CN': { name: '塞切尼温泉浴场', narration: '欢迎来到欧洲最大的公共温泉塞切尼。', description: '1913年开业的欧洲最大公共温泉浴场。' } }, searchKeywords: ['세체니 온천', '부다페스트 온천', 'Széchenyi', 'thermal bath', 'Budapest spa'] },
            { id: 'budapest_fishermans_bastion', name: 'Fisherman\'s Bastion', lat: 47.5019, lng: 19.0348, narration: '부다 성 언덕 위에 자리한 어부의 요새에서 다뉴브 강과 페스트 시가지의 파노라마를 감상하세요. 7개의 하얀 탑은 9세기 마자르 족 7부족을 상징하며, 네오로마네스크 양식의 우아한 테라스는 부다페스트 최고의 전망대입니다.', description: 'Fairy-tale Neo-Romanesque terrace on Castle Hill with panoramic views of the Danube and Pest.', category: 'Landmark', photos: ['https://images.unsplash.com/photo-1565426873118-a17ed65d74b9?w=1200&q=80', 'https://images.unsplash.com/photo-1549923746-c502d488b3ea?w=1200&q=80', 'https://images.unsplash.com/photo-1551867633-194f125bddfa?w=1200&q=80'], translations: { ko: { name: '어부의 요새', narration: '부다 성 언덕 위의 어부의 요새에서 다뉴브 강 파노라마를 감상하세요.', description: '7개 하얀 탑과 함께 다뉴브 강 파노라마를 선사하는 동화 같은 전망대.' }, en: { name: 'Fisherman\'s Bastion', narration: 'Enjoy panoramic views of the Danube from the fairy-tale Fisherman\'s Bastion.', description: 'Neo-Romanesque terrace on Castle Hill with 7 towers symbolizing the Magyar tribes.' }, ja: { name: '漁夫の砦', narration: 'ブダ城の丘にある漁夫の砦からドナウ川のパノラマを楽しみましょう。', description: '7つの白い塔を持つおとぎ話のようなネオロマネスク様式の展望テラス。' }, 'zh-CN': { name: '渔夫堡', narration: '从布达城堡山上的渔夫堡俯瞰多瑙河全景。', description: '城堡山上童话般的新罗马式露台，7座白塔象征马扎尔七部落。' } }, searchKeywords: ['어부의 요새', '부다페스트', 'Fisherman\'s Bastion', 'Castle Hill', '다뉴브 전망'] },
            { id: 'budapest_ruin_bars', name: 'Szimpla Kert Ruin Bar', lat: 47.4974, lng: 19.0629, narration: '부다페스트의 독특한 문화 아이콘, 루인 바의 원조 심플라 케르트에 오신 것을 환영합니다. 2002년 버려진 공장 건물을 개조해 만든 이 바는 빈티지 가구, 그래피티, 식물들이 독특하게 어우러진 분위기로 전 세계 여행자들의 필수 방문지가 되었습니다.', description: 'The original Budapest ruin bar in a converted factory, birthplace of the city\'s iconic nightlife culture.', category: 'Cultural Site', photos: ['https://images.unsplash.com/photo-1551867633-194f125bddfa?w=1200&q=80', 'https://images.unsplash.com/photo-1549923746-c502d488b3ea?w=1200&q=80', 'https://images.unsplash.com/photo-1565426873118-a17ed65d74b9?w=1200&q=80'], translations: { ko: { name: '심플라 케르트 루인 바', narration: '부다페스트 루인 바의 원조 심플라 케르트에 오신 것을 환영합니다.', description: '버려진 공장을 개조한 부다페스트 루인 바 문화의 원조.' }, en: { name: 'Szimpla Kert Ruin Bar', narration: 'Welcome to Szimpla Kert, the original Budapest ruin bar.', description: 'The pioneering ruin bar in a converted factory, birthplace of Budapest\'s nightlife culture.' }, ja: { name: 'シンプラ・ケルト廃墟バー', narration: 'ブダペスト廃墟バー文化の元祖シンプラ・ケルトへようこそ。', description: '廃工場を改装したブダペスト廃墟バー文化の発祥地。' }, 'zh-CN': { name: '辛普拉花园废墟酒吧', narration: '欢迎来到布达佩斯废墟酒吧的鼻祖辛普拉花园。', description: '将废弃工厂改造成的布达佩斯标志性废墟酒吧文化发源地。' } }, searchKeywords: ['루인 바', '심플라 케르트', '부다페스트 나이트', 'Szimpla', 'ruin bar', 'Budapest nightlife'] }
        ]
    },
    warsaw: {
        lat: 52.2297, lng: 21.0122, landmarks: [
            { id: 'warsaw_old_town', name: 'Warsaw Old Town', lat: 52.2496, lng: 21.0122, narration: '제2차 세계대전 중 85% 이상 파괴되었다가 시민들의 헌신적인 노력으로 완벽하게 복원된 바르샤바 구시가지에 오신 것을 환영합니다. 유네스코 세계문화유산으로 지정된 이 구시가지는 도시의 불굴의 정신을 나타냅니다.', description: 'UNESCO World Heritage old town, painstakingly rebuilt after WWII from 85% destruction.', category: 'Historic Site', photos: ['https://images.unsplash.com/photo-1519197924294-4ba991a11128?w=1200&q=80', 'https://images.unsplash.com/photo-1607427293702-036707e560d7?w=1200&q=80', 'https://images.unsplash.com/photo-1587825140708-dfaf18c4c5ec?w=1200&q=80'], translations: { ko: { name: '바르샤바 구시가지', narration: '전쟁 후 완벽하게 복원된 유네스코 세계문화유산 구시가지입니다.', description: 'WWII 후 시민들이 복원한 유네스코 세계문화유산 구시가지.' }, en: { name: 'Warsaw Old Town', narration: 'Welcome to Warsaw\'s Old Town, rebuilt from 85% destruction after WWII.', description: 'UNESCO Heritage old town, meticulously reconstructed after WWII devastation.' }, ja: { name: 'ワルシャワ旧市街', narration: '第二次大戦後に市民の手で完璧に復元されたユネスコ世界遺産の旧市街です。', description: '第二次大戦で85%破壊後、再建されたユネスコ世界遺産。' }, 'zh-CN': { name: '华沙老城', narration: '二战中85%被毁后由市民完美重建的联合国教科文组织世界遗产老城。', description: '二战后精心重建的联合国教科文组织世界遗产老城。' } }, searchKeywords: ['바르샤바 구시가지', '유네스코', 'Warsaw Old Town', 'UNESCO', 'WWII reconstruction'] },
            { id: 'warsaw_wilanow_palace', name: 'Wilanów Palace', lat: 52.1654, lng: 21.0904, narration: '폴란드의 베르사유라 불리는 빌라누프 궁전에 오신 것을 환영합니다. 1677년 얀 3세 소비에스키 왕이 여름 별궁으로 건설한 이 바로크 양식의 궁전은 아름다운 정원과 함께 폴란드 왕실의 영화를 보여줍니다.', description: 'The \'Polish Versailles\' — a magnificent Baroque summer palace built for King Jan III Sobieski in 1677.', category: 'Landmark', photos: ['https://images.unsplash.com/photo-1607427293702-036707e560d7?w=1200&q=80', 'https://images.unsplash.com/photo-1519197924294-4ba991a11128?w=1200&q=80', 'https://images.unsplash.com/photo-1587825140708-dfaf18c4c5ec?w=1200&q=80'], translations: { ko: { name: '빌라누프 궁전', narration: '폴란드의 베르사유, 빌라누프 궁전에 오신 것을 환영합니다.', description: '1677년 건설된 폴란드의 베르사유로 불리는 바로크 여름 별궁.' }, en: { name: 'Wilanów Palace', narration: 'Welcome to the Polish Versailles, Wilanów Palace.', description: 'Magnificent Baroque palace built 1677 for King Jan III Sobieski.' }, ja: { name: 'ヴィラヌフ宮殿', narration: 'ポーランドのヴェルサイユ、ヴィラヌフ宮殿へようこそ。', description: '1677年建設のポーランドのヴェルサイユと呼ばれるバロック宮殿。' }, 'zh-CN': { name: '维拉诺夫宫', narration: '欢迎来到波兰的凡尔赛宫——维拉诺夫宫。', description: '1677年为国王扬三世建造的巴洛克风格夏宫。' } }, searchKeywords: ['빌라누프', '바르샤바 궁전', 'Wilanów', 'Polish Versailles', 'Sobieski'] }
        ]
    },
    copenhagen: {
        lat: 55.6761, lng: 12.5683, landmarks: [
            { id: 'copenhagen_nyhavn', name: 'Nyhavn Waterfront', lat: 55.6796, lng: 12.5893, narration: '코펜하겐의 상징 뉘하운 항구에 오신 것을 환영합니다. 17세기에 건설된 이 항구를 따라 빨강, 노랑, 파랑의 화려한 색상으로 칠해진 타운하우스들이 늘어서 있으며, 동화 작가 한스 크리스티안 안데르센이 살았던 집도 이곳에 있습니다.', description: 'Copenhagen\'s iconic 17th-century harbor lined with colorful townhouses and Hans Christian Andersen\'s home.', category: 'Landmark', photos: ['https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=1200&q=80', 'https://images.unsplash.com/photo-1552560880-2482d4b1e4e2?w=1200&q=80', 'https://images.unsplash.com/photo-1532885270927-2fcc56d6d1f2?w=1200&q=80'], translations: { ko: { name: '뉘하운 항구', narration: '17세기 항구를 따라 다채로운 건물들이 늘어선 코펜하겐의 상징입니다.', description: '안데르센이 살았던 곳, 17세기 다채로운 타운하우스가 즐비한 항구.' }, en: { name: 'Nyhavn Waterfront', narration: 'Welcome to Nyhavn, Copenhagen\'s most iconic waterfront.', description: 'Iconic 17th-century harbor with colorful townhouses, once home to Hans Christian Andersen.' }, ja: { name: 'ニューハウン港', narration: 'コペンハーゲンのシンボル、ニューハウン港へようこそ。', description: 'アンデルセンが住んだ17世紀のカラフルな港。' }, 'zh-CN': { name: '新港', narration: '欢迎来到哥本哈根的标志性景点新港。', description: '安徒生故居所在的17世纪彩色建筑港口。' } }, searchKeywords: ['뉘하운', '코펜하겐', '안데르센', 'Nyhavn', 'Copenhagen', 'Andersen'] },
            { id: 'copenhagen_tivoli', name: 'Tivoli Gardens', lat: 55.6737, lng: 12.5681, narration: '1843년에 개장한 세계에서 두 번째로 오래된 놀이공원 티볼리 가든에 오신 것을 환영합니다. 월트 디즈니가 디즈니랜드의 영감을 받은 곳으로, 놀이기구, 정원, 레스토랑, 콘서트홀이 아름답게 어우러진 마법의 공간입니다.', description: 'The world\'s second-oldest amusement park (1843), Walt Disney\'s inspiration for Disneyland.', category: 'Activity', photos: ['https://images.unsplash.com/photo-1552560880-2482d4b1e4e2?w=1200&q=80', 'https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=1200&q=80', 'https://images.unsplash.com/photo-1532885270927-2fcc56d6d1f2?w=1200&q=80'], translations: { ko: { name: '티볼리 가든', narration: '1843년 개장, 디즈니랜드의 영감이 된 마법의 놀이공원입니다.', description: '1843년 개장, 디즈니랜드의 모델이 된 세계에서 두 번째로 오래된 놀이공원.' }, en: { name: 'Tivoli Gardens', narration: 'Welcome to Tivoli Gardens, the magical 1843 park that inspired Disneyland.', description: 'World\'s second-oldest amusement park, Walt Disney\'s inspiration for Disneyland.' }, ja: { name: 'チボリ公園', narration: '1843年開園、ディズニーランドの着想源となった魔法の遊園地へようこそ。', description: '1843年開園、ディズニーランドのモデルとなった世界で2番目に古い遊園地。' }, 'zh-CN': { name: '趣伏里花园', narration: '欢迎来到1843年开园的趣伏里花园，这里是迪士尼乐园的灵感来源。', description: '1843年开园，启发了迪士尼乐园的世界第二古老游乐园。' } }, searchKeywords: ['티볼리', '코펜하겐', 'Tivoli', 'Copenhagen', '디즈니랜드 영감', 'Disney inspiration'] }
        ]
    },
    oslo: {
        lat: 59.9139, lng: 10.7522, landmarks: [
            { id: 'oslo_opera_house', name: 'Oslo Opera House', lat: 59.9077, lng: 10.7529, narration: '오슬로 피오르드 가장자리에 자리한 오슬로 오페라하우스는 바다에서 솟아오른 빙하를 연상시키는 현대 건축의 걸작입니다. 기울어진 하얀 대리석 지붕 위를 걸어 올라가면 오슬로 피오르드와 도시 전경이 펼쳐집니다.', description: 'Award-winning modern opera house with a walkable marble roof rising from Oslo Fjord.', category: 'Landmark', photos: ['https://images.unsplash.com/photo-1533929736562-87b04b9ca07a?w=1200&q=80', 'https://images.unsplash.com/photo-1559629819-638a8f0a4303?w=1200&q=80', 'https://images.unsplash.com/photo-1579013100096-23b5f4d1b8cf?w=1200&q=80'], translations: { ko: { name: '오슬로 오페라하우스', narration: '피오르드에서 솟아오른 빙하 같은 현대 건축의 걸작입니다.', description: '피오르드에서 솟아오른 듯한 걸어 올라갈 수 있는 대리석 지붕의 오페라하우스.' }, en: { name: 'Oslo Opera House', narration: 'The Oslo Opera House rises from the fjord like a glacier.', description: 'Iconic modern opera house with a walkable marble roof on Oslo Fjord.' }, ja: { name: 'オスロ・オペラハウス', narration: 'フィヨルドから氷河のようにそびえ立つ現代建築の傑作です。', description: 'フィヨルドから立ち上がる歩行可能な大理石屋根を持つオペラハウス。' }, 'zh-CN': { name: '奥斯陆歌剧院', narration: '奥斯陆歌剧院如冰川般从峡湾中升起。', description: '峡湾畔可步行上屋顶的标志性现代歌剧院。' } }, searchKeywords: ['오페라하우스', '오슬로', 'Opera House', 'Oslo', '피오르드 건축'] },
            { id: 'oslo_vigeland_park', name: 'Vigeland Sculpture Park', lat: 59.9269, lng: 10.7008, narration: '세계 최대 규모의 단일 작가 조각 공원, 비겔란 공원에 오신 것을 환영합니다. 노르웨이 조각가 구스타프 비겔란이 평생을 바쳐 제작한 212점의 조각품이 80에이커의 광활한 공원에 전시되어 있습니다.', description: 'World\'s largest single-artist sculpture park with 212 works by Gustav Vigeland.', category: 'Cultural Site', photos: ['https://images.unsplash.com/photo-1559629819-638a8f0a4303?w=1200&q=80', 'https://images.unsplash.com/photo-1533929736562-87b04b9ca07a?w=1200&q=80', 'https://images.unsplash.com/photo-1579013100096-23b5f4d1b8cf?w=1200&q=80'], translations: { ko: { name: '비겔란 조각 공원', narration: '세계 최대의 단일 작가 조각 공원에 오신 것을 환영합니다.', description: '구스타프 비겔란의 212점 조각이 있는 세계 최대 단일 작가 조각 공원.' }, en: { name: 'Vigeland Sculpture Park', narration: 'Welcome to the world\'s largest single-artist sculpture park.', description: '212 sculptures by Gustav Vigeland spanning the human condition in an 80-acre park.' }, ja: { name: 'ヴィーゲラン彫刻公園', narration: '世界最大の単一アーティスト彫刻公園へようこそ。', description: 'グスタフ・ヴィーゲランの212作品を展示する世界最大の彫刻公園。' }, 'zh-CN': { name: '维格兰雕塑公园', narration: '欢迎来到世界最大的单一艺术家雕塑公园。', description: '展示古斯塔夫·维格兰212件雕塑作品的世界最大单一艺术家雕塑公园。' } }, searchKeywords: ['비겔란', '오슬로 조각', 'Vigeland', 'sculpture park', 'Oslo'] }
        ]
    },
    brussels: {
        lat: 50.8503, lng: 4.3517, landmarks: [
            { id: 'brussels_grand_place', name: 'Grand-Place / Grote Markt', lat: 50.8467, lng: 4.3525, narration: '유네스코 세계문화유산이자 빅트르 위고가 세계에서 가장 아름다운 광장이라 극찬한 그랑플라스에 오신 것을 환영합니다. 황금빛 바로크 건물들이 둘러싼 이 광장은 브뤼셀의 영혼 그 자체입니다.', description: 'UNESCO World Heritage square praised by Victor Hugo as the world\'s most beautiful.', category: 'Landmark', photos: ['https://images.unsplash.com/photo-1559113513-d5e09c78a5ab?w=1200&q=80', 'https://images.unsplash.com/photo-1562228378-b1f3a7ee8a07?w=1200&q=80', 'https://images.unsplash.com/photo-1600622844439-84307069b122?w=1200&q=80'], translations: { ko: { name: '그랑플라스', narration: '빅트르 위고가 세계에서 가장 아름다운 광장이라 극찬한 유네스코 유산입니다.', description: '빅트르 위고가 극찬한 유네스코 세계문화유산 광장.' }, en: { name: 'Grand-Place / Grote Markt', narration: 'Welcome to the Grand-Place, called the most beautiful square by Victor Hugo.', description: 'UNESCO World Heritage square surrounded by golden Baroque guild halls.' }, ja: { name: 'グラン＝プラス', narration: 'ヴィクトル・ユーゴーが世界一美しい広場と絶賛したグラン＝プラスへようこそ。', description: 'ユネスコ世界遺産、黄金のバロック建築に囲まれた広場。' }, 'zh-CN': { name: '大广场', narration: '欢迎来到被维克多·雨果赞誉为世界最美广场的大广场。', description: '被金色巴洛克行会大厦环绕的联合国教科文组织世界遗产广场。' } }, searchKeywords: ['그랑플라스', '브뤼셀', 'Grand-Place', 'Brussels', 'UNESCO', '빅트르 위고'] },
            { id: 'brussels_atomium', name: 'Atomium', lat: 50.8948, lng: 4.3418, narration: '1958년 세계 박람회를 위해 건설된 아토미움은 철 결정 구조를 1650억 배로 확대한 102m 높이의 독특한 건축물입니다. 9개의 구체가 연결된 이 미래적 구조물은 브뤼셀의 가장 상징적인 랜드마크입니다.', description: 'Iconic 102m structure of nine connected spheres, built for the 1958 World Expo.', category: 'Landmark', photos: ['https://images.unsplash.com/photo-1562228378-b1f3a7ee8a07?w=1200&q=80', 'https://images.unsplash.com/photo-1559113513-d5e09c78a5ab?w=1200&q=80', 'https://images.unsplash.com/photo-1600622844439-84307069b122?w=1200&q=80'], translations: { ko: { name: '아토미움', narration: '1958년 세계 박람회를 위해 건설된 102m 높이의 아토미움입니다.', description: '철 결정 구조를 1650억 배 확대한 1958년 세계 박람회의 상징.' }, en: { name: 'Atomium', narration: 'The Atomium rises 102 metres, built for the 1958 World Expo.', description: 'Iconic 102m iron crystal structure magnified 165 billion times, built for Expo 1958.' }, ja: { name: 'アトミウム', narration: '1958年万博のために建設された102mの鉄の結晶構造アトミウムです。', description: '1958年万博のシンボル、鉄の結晶を1650億倍に拡大した102mの構造物。' }, 'zh-CN': { name: '原子球塔', narration: '为1958年世博会建造的102米高原子球塔。', description: '1958年世博会标志，将铁晶体结构放大1650亿倍的102米建筑。' } }, searchKeywords: ['아토미움', '브뤼셀', 'Atomium', 'Brussels', '1958 Expo', '세계 박람회'] }
        ]
    },
    prague: {
        lat: 50.0755, lng: 14.4378, landmarks: [
            { id: 'prague_charles_bridge', name: 'Charles Bridge', lat: 50.0865, lng: 14.4114, narration: '1357년 카를 4세의 명에 의해 건설된 카를교 위에 서 계십니다. 블타바 강을 가로지르는 이 516m의 고딕 석조 다리 위에는 30개의 바로크 성인 조각상이 늘어서 있으며, 프라하 성과 구시가지를 잇는 역사적 통로입니다.', description: 'Gothic 14th-century stone bridge with 30 Baroque saint statues spanning the Vltava River.', category: 'Landmark', photos: ['https://images.unsplash.com/photo-1541849546-216549ae216d?w=1200&q=80', 'https://images.unsplash.com/photo-1562624475-96c2bc08fab9?w=1200&q=80', 'https://images.unsplash.com/photo-1519677100203-a0e668c92439?w=1200&q=80'], translations: { ko: { name: '카를교', narration: '1357년 건설된 30개 성인 조각상이 서 있는 고딕 석조 다리입니다.', description: '블타바 강 위 30개 바로크 성인 조각이 있는 14세기 고딕 석조 다리.' }, en: { name: 'Charles Bridge', narration: 'Standing on Charles Bridge, built in 1357 by order of Emperor Charles IV.', description: '14th-century Gothic stone bridge with 30 Baroque saint statues spanning the Vltava.' }, ja: { name: 'カレル橋', narration: '1357年にカール4世の命で建設されたカレル橋の上に立っています。', description: 'ヴルタヴァ川に架かる30体のバロック聖人像が並ぶ14世紀のゴシック石橋。' }, 'zh-CN': { name: '查理大桥', narration: '您正站在1357年查理四世下令建造的查理大桥上。', description: '横跨伏尔塔瓦河的14世纪哥特式石桥，桥上排列30座巴洛克圣人雕像。' } }, searchKeywords: ['카를교', '프라하', 'Charles Bridge', 'Prague', '블타바 강', '고딕'] },
            { id: 'prague_old_town_square', name: 'Old Town Square & Astronomical Clock', lat: 50.0873, lng: 14.4213, narration: '프라하의 심장, 구시가지 광장과 600년 역사의 천문 시계 앞에 서 계십니다. 1410년에 제작된 이 천문 시계는 세계에서 가장 오래된 작동 중인 천문 시계로, 매 정시마다 12사도의 행렬이 펼쳐집니다.', description: 'Prague\'s medieval heart featuring the 1410 Astronomical Clock, the world\'s oldest still-operating.', category: 'Historic Site', photos: ['https://images.unsplash.com/photo-1562624475-96c2bc08fab9?w=1200&q=80', 'https://images.unsplash.com/photo-1541849546-216549ae216d?w=1200&q=80', 'https://images.unsplash.com/photo-1519677100203-a0e668c92439?w=1200&q=80'], translations: { ko: { name: '구시가지 광장 & 천문 시계', narration: '1410년 제작된 세계에서 가장 오래된 천문 시계가 있는 구시가지 광장입니다.', description: '1410년 세계 최고(最古) 천문 시계가 있는 프라하의 중세 심장부.' }, en: { name: 'Old Town Square & Astronomical Clock', narration: 'The 1410 Astronomical Clock is the oldest still-operating in the world.', description: 'Medieval heart of Prague with the 1410 Astronomical Clock and hourly Apostle procession.' }, ja: { name: '旧市街広場＆天文時計', narration: '1410年製の世界最古の作動中天文時計がある旧市街広場です。', description: '1410年の天文時計と毎正時の使徒行列が名物のプラハの中世の中心地。' }, 'zh-CN': { name: '老城广场与天文钟', narration: '1410年制造的世界最古老仍在运行的天文钟就在眼前。', description: '拥有1410年天文钟的布拉格中世纪心脏地带。' } }, searchKeywords: ['구시가지 광장', '천문 시계', '프라하', 'Old Town Square', 'Astronomical Clock', 'Prague', '1410'] }
        ]
    },
    stockholm: {
        lat: 59.3293, lng: 18.0686, landmarks: [
            { id: 'stockholm_gamla_stan', name: 'Gamla Stan (Old Town)', lat: 59.3252, lng: 18.0710, narration: '13세기에 형성된 스톡홀름의 구시가지 감라 스탄에 오신 것을 환영합니다. 발트해의 작은 섬 위에 자리한 이 중세 마을은 좁은 골목길, 왕궁, 노벨 박물관, 그리고 스톡홀름 대성당 등 스웨덴 역사의 보물이 가득합니다.', description: 'Stockholm\'s 13th-century island old town with medieval streets, the Royal Palace, and Nobel Museum.', category: 'Historic Site', photos: ['https://images.unsplash.com/photo-1509356843151-3e7d96241e11?w=1200&q=80', 'https://images.unsplash.com/photo-1572883454114-efb8e12fd1a2?w=1200&q=80', 'https://images.unsplash.com/photo-1577971132997-a38115d4a3de?w=1200&q=80'], translations: { ko: { name: '감라 스탄 (구시가지)', narration: '13세기에 형성된 발트해 섬 위의 중세 구시가지입니다.', description: '중세 골목, 왕궁, 노벨 박물관이 있는 13세기 섬 구시가지.' }, en: { name: 'Gamla Stan (Old Town)', narration: 'Welcome to Gamla Stan, Stockholm\'s 13th-century island old town.', description: '13th-century island old town with medieval streets, the Royal Palace, and Nobel Museum.' }, ja: { name: 'ガムラスタン（旧市街）', narration: '13世紀に形成されたバルト海の島にある旧市街ガムラスタンへようこそ。', description: '中世の路地、王宮、ノーベル博物館がある13世紀の島の旧市街。' }, 'zh-CN': { name: '老城岛', narration: '欢迎来到13世纪形成的波罗的海岛上的中世纪老城。', description: '拥有中世纪街道、王宫和诺贝尔博物馆的13世纪岛屿老城。' } }, searchKeywords: ['감라 스탄', '스톡홀름 구시가지', 'Gamla Stan', 'Stockholm', 'Old Town', '노벨 박물관'] },
            { id: 'stockholm_vasa_museum', name: 'Vasa Museum', lat: 59.3280, lng: 18.0914, narration: '1628년 처녀 항해에서 침몰한 군함 바사호가 333년 만에 해저에서 인양되어 전시된 바사 박물관에 오신 것을 환영합니다. 거의 완벽한 상태로 보존된 17세기 전함은 세계에서 가장 잘 보존된 역사적 선박입니다.', description: 'Museum housing the Vasa warship, sunk in 1628 and salvaged 333 years later nearly intact.', category: 'Museum', photos: ['https://images.unsplash.com/photo-1572883454114-efb8e12fd1a2?w=1200&q=80', 'https://images.unsplash.com/photo-1509356843151-3e7d96241e11?w=1200&q=80', 'https://images.unsplash.com/photo-1577971132997-a38115d4a3de?w=1200&q=80'], translations: { ko: { name: '바사 박물관', narration: '1628년 침몰, 333년 후 인양된 군함 바사호가 전시된 박물관입니다.', description: '1628년 침몰 후 333년 만에 인양된 17세기 전함 전시 박물관.' }, en: { name: 'Vasa Museum', narration: 'The Vasa warship sank in 1628 and was salvaged 333 years later, nearly intact.', description: 'Home to the 1628 warship Vasa, salvaged after 333 years and nearly perfectly preserved.' }, ja: { name: 'ヴァーサ号博物館', narration: '1628年に沈没し333年後に引き揚げられた軍艦ヴァーサ号の博物館です。', description: '1628年沈没後333年ぶりに引き揚げられた17世紀軍艦を展示する博物館。' }, 'zh-CN': { name: '瓦萨博物馆', narration: '1628年沉没、333年后打捞上来的瓦萨号战舰博物馆。', description: '展示1628年沉没后333年被打捞、几乎完好无损的17世纪战舰。' } }, searchKeywords: ['바사 박물관', '스톡홀름', 'Vasa Museum', 'Stockholm', '1628', '전함'] }
        ]
    }
};

// Build file content
let output = `import { type Landmark } from "../../shared/schema";\n\nexport const LANDMARKS_EU_BOOST: Landmark[] = [\n`;

for (const [cityId, cityData] of Object.entries(cities)) {
    output += `  // ============================================================\n`;
    output += `  // ${cityId.toUpperCase()}\n`;
    output += `  // ============================================================\n`;
    for (const lm of cityData.landmarks) {
        output += `  {\n`;
        output += `    "id": "${lm.id}",\n`;
        output += `    "cityId": "${cityId}",\n`;
        output += `    "name": ${JSON.stringify(lm.name)},\n`;
        output += `    "lat": ${lm.lat},\n`;
        output += `    "lng": ${lm.lng},\n`;
        output += `    "radius": 80,\n`;
        output += `    "narration": ${JSON.stringify(lm.narration)},\n`;
        output += `    "description": ${JSON.stringify(lm.description)},\n`;
        output += `    "category": ${JSON.stringify(lm.category)},\n`;
        output += `    "detailedDescription": null,\n`;
        output += `    "photos": ${JSON.stringify(lm.photos)},\n`;
        output += `    "historicalInfo": null,\n`;
        output += `    "yearBuilt": null,\n`;
        output += `    "architect": null,\n`;
        output += `    "translations": ${JSON.stringify(lm.translations, null, 6).split('\n').map((l, i) => i === 0 ? l : '    ' + l).join('\n')},\n`;
        output += `    "openingHours": null,\n`;
        output += `    "priceRange": null,\n`;
        output += `    "cuisine": null,\n`;
        output += `    "reservationUrl": null,\n`;
        output += `    "phoneNumber": null,\n`;
        output += `    "menuHighlights": null,\n`;
        output += `    "restaurantPhotos": null,\n`;
        output += `    "paymentMethods": null,\n`;
        output += `    "searchKeywords": ${JSON.stringify(lm.searchKeywords)},\n`;
        output += `    "isPremium": false,\n`;
        output += `    "price": null,\n`;
        output += `    "createdAt": new Date("2026-04-22T00:00:00.000Z"),\n`;
        output += `    "updatedAt": new Date("2026-04-22T00:00:00.000Z")\n`;
        output += `  },\n`;
    }
}
output += `];\n`;

const outPath = path.join(__dirname, '..', 'server', 'data', 'landmarks_eu_boost.ts');
fs.writeFileSync(outPath, output, 'utf-8');
console.log(`✅ EU Boost landmarks written to ${outPath} (${output.split('\n').length} lines)`);
